### ISSUE TITLE
An example?

### ISSUE THREAD

**Issue by HZSamir** [pixelstew/gatsby-paginate#1]
Would be most helpful
~~Preferably with something like wordpress...~~
Thank you

**Comment by kalinchernev** [comment]
I'm landing on this repo after reading a discussion about wishlist of plugins. There is a link where @pixelstew mentions [an example](https://github.com/gatsbyjs/gatsby/issues/1199#issuecomment-335461686). I'm about to test whether the implementation there is coming from the era before the plugin abstraction or not :)

**Comment by pixelstew** [comment]
HI there, Apologies but work has picked up pace so I haven't had much time to add anything. I will try to do so this week.

**Comment by pixelstew** [comment]
In place of writing a specific example - please check the [blog](https://github.com/pixelstew/pixelstew-gatsby) I'm building for myself. It is all open source. 

Check `gatsby-node.js` and `.src/templates/paginatedPostList.js` for my implementation.

**Comment by kalinchernev** [comment]
@pixelstew I took almost same approach as you mention in your blog.
I guess you've already seen the #3 where @technovangelist has written the approach in words.
