### ISSUE TITLE
Path Prefix is ignored for first page

### ISSUE THREAD

**Issue by e1moreno** [pixelstew/gatsby-paginate#14]
Trying to use path prefix to assist me with localization. What I am finding is that the first page is always created at root '/' and subsequent pages are working correctly.

My developer 404, basically shows
/
/en/2
/en/3
/en/4

The path prefix is being ignored completely on the first page. Is this intended?

**Comment by amitpatra** [comment]
The latest version is not published yet on npm I believe.

**Comment by pixelstew** [comment]
Hi there @Garbonauta Pull the package from npm again - should respect prefix for first page now

**Comment by e1moreno** [comment]
@pixelstew Works great! Thank you very much!
