### ISSUE TITLE
Allow to pass custom context

### ISSUE THREAD

**Issue by szimek** [pixelstew/gatsby-paginate#21]
First of all, thanks a lot for this plugin!

It looks like this feature already existed, but was later removed. Why?

Wouldn't it be enough to add `context` as a source to `Object.assign` call?

```js
context: Object.assign(
  {},
  {
    group,
    pathPrefix,
    ...
  },
  context
)
```
? 

Or, if there's a risk that user could accidentally overwrite pagination context, switch pagination props with context.

**Comment by pixelstew** [comment]
No problem - glad I could add something of use to people. 

Yeah I plan to put it back in. Previous PR was not backwards compatible though which I stupidly published before noticing. Will add again shortly with the implementation above.

**Comment by pixelstew** [comment]
https://github.com/pixelstew/gatsby-paginate/pull/22

This is now in place
