### ISSUE TITLE
Empty path calculated for first page breaking build

### ISSUE THREAD

**Issue by chrissearle** [pixelstew/gatsby-paginate#46]
Updated my dependencies (gatsby, plugins etc) to the lastest releases today and am now getting this error at build:

    ERROR #11323
    Your site's "gatsby-node.js" must set the page path when creating a page

It happens on this code:

        createPaginatedPages({
          edges: result.data.allMarkdownRemark.edges,
          createPage: createPage,
          pageTemplate: 'src/templates/index.js',
          pageLength: 20,
        })

Looking at the error - it's the very first page.

Path is calculated in paginate as:

    path:
        typeof buildPath === `function`
          ? buildPath(pageIndex, pathPrefix)
          : buildPaginationRoute(pageIndex, pathPrefix),

Here I am not passing a buildPath function - so that is null and therefore it calls buildPaginationRoute. 

    const buildPaginationRoute = (index, pathPrefix) =>
        index > 1 ? `${pathPrefix}/${index}` : pathPrefix

Index is the empty string on the first page (I think).

So this returns just pathPrefix - but - I am not using pathPrefix for the main index of the site - so that's the empty string.

I suspect that it's related to this change in gatsby:

https://github.com/gatsbyjs/gatsby/commit/44654be688230e530894456891a73a1562acfb9a#diff-c739d0ad63537276e8fc320522a8b985

If you look at the code there you can see that before the change - if the path was the empty string it would do this:

      console.log(chalk.bold.red(message))
      console.log(``)
      console.log(page)

But now it does this:

     report.panic({
        id: `11323`,
        context: {
          pluginName: name,
          pageObject: page,
          message,
        },
      })

If I understood the gatsby code then it means that after this change - it will no longer log and continue but abort a build if we call paginate with no pathPrefix and no buildPath function when creating the first page?

**Comment by Randyjp** [comment]
I had the same issue, great reporting @chrissearle ; I went ahead an opened a #47  to fix this.

**Comment by janosh** [comment]
[Fix published as v1.1.1](https://www.npmjs.com/package/gatsby-paginate).
