### ISSUE TITLE
createPaginatedPages should pass ‘count’ parameter to template for ease of use.

### ISSUE THREAD

**Issue by haysclark** [pixelstew/gatsby-paginate#5]
Providing the 'count' for the number of page groups created would greatly ease the creation footers stating _index_ of _count_. 

e.g. __Page 1 of 20__

New parameter handed to the template from _createPaginatedPages_:
```
{
  group: []
  first: boolean,
  last: boolean,
  index: int,
  count: int
}
```

**Comment by pixelstew** [comment]
Similar solution merged #10
