### ISSUE TITLE
Create post listing not at project root

### ISSUE THREAD

**Issue by Sorgrum** [pixelstew/gatsby-paginate#9]
Would it be possible to add a config option for creating the paginated post listing outside of the root of the document?

For example, instead of being at `0.0.0.0:8000/` it could be at `0.0.0.0:8000/blog`

**Comment by pixelstew** [comment]
Yes this should be possible, will take a look this evening. Apologies if I go dark on this repo - very busy at work at the moment.

**Comment by uttrasey** [comment]
@Sorgrum It looks like this is possible using the undocumented [paginatePost](https://github.com/pixelstew/gatsby-paginate/blob/master/src/index.js#L42) config. In your case it would be as per below:

```
createPaginatedPages({
    edges: result.data.posts.edges,
    createPage: createPage,
    pageTemplate: "src/templates/index.js",
    pageLength: 10,
    paginatePost: "blog"
});
```

**Comment by pixelstew** [comment]
@Sorgrum Yes @uttrasey is correct - i will update docs for new features soon.

Closing issue
